[project]
name = "home-credit-risk-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alymbaek", email = "alymbekibragimov46@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
home-credit-risk-ml = "home_credit_risk_ml:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
